nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "5555:80"
node1:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
    environment:
        - MY_NAME=node1
        - TEST_URL=http://54.254.223.84:5555/
node2:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
    environment:
        - MY_NAME=node2
        - TEST_URL=http://54.254.223.84:5555/
node3:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
    environment:
        - MY_NAME=node3
        - TEST_URL=http://54.254.223.84:5555/
redis:
    image: redis
    ports:
        - "6379"
